project:
  type: website

website:
  title: "Leong Zhuan Kee, Vis"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    left:
      - href: cv.qmd
        text: CV
    
      
format:
  html:
    theme: [cosmo, styles.scss]

